#
# Makefile for the LEAPIORAID drivers.
#

obj-$(CONFIG_SCSI_LEAPIORAID) += leapioraid.o
leapioraid-objs += leapioraid_func.o	\
				leapioraid_os.o	\
				leapioraid_transport.o	\
				leapioraid_app.o